name: Auto Author Assign

on:
  pull_request:
    branches:
      - staging
      - production
    types:
      - opened
      - reopened

permissions:
  pull-requests: write

jobs:
  assign_author:
    name: Assign Author
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v2.1.0
